# Do not change the 'definitions' section unless you know what you're doing
definitions:
  synapse_config: ".synapseConfig"
  creds_path: "credentials.json"
  token_pickle: "token.pickle"
  service_acct_creds: "quickstart-1560359685924-198a7114b6b5.json"

synapse:
  master_fileview: 'syn20446927'
  manifest_folder: 'manifests'
  manifest_filename: 'data/manifests/synapse_storage_manifest.csv'
  api_creds: 'syn21088684'

manifest:
  title: 'Patient_Manifest'
  data_type: 'Patient'

model:
  input:
    location: 'data/schema_org_schemas/example.jsonld'
    file_type: 'local'
    validation_schema: 'data/validation_schemas/example_validation_schema.json'
    log_location: 'data/json_schema_logs/json_schema_log.json'

style:
  google_manifest:
    req_bg_color:
      red: 0.9215
      green: 0.9725
      blue: 0.9803
    opt_bg_color:
      red: 1.0
      green: 1.0
      blue: 0.9019
    master_template_id: '1LYS5qE4nV9jzcYw5sXwCza25slDfRA1CIg3cs-hCdpU'
